# Site settings
title: Joshua Reid Adams Portfolio
description: Application Development Student | Software Developer in Training

# Use Hacker theme
remote_theme: pages-themes/hacker@v0.2.0

# Required plugin
plugins:
  - jekyll-remote-theme

# Optional settings
show_downloads: false
timezone: Africa/Johannesburg